swagger: "2.0"
info:
  description: "API spec for paperclip"
  version: "1.0.0"
  title: "Swagger Paperclip"
host: "raw.githubusercontent.com"
basePath: "/leboncoin/paperclip/master"
schemes:
  - "https"
paths:
  /listing.json:
    get:
      summary: "list of classified ads"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ClassifiedAd"
  /categories.json:
    get:
      summary: "list of categories"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Category"
definitions:
  Category:
    type: "object"
    required:
      - "id"
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
  ClassifiedAd:
    type: "object"
    required:
      - "id"
      - "title"
      - "category_id"
      - "creation_date"
      - "description"
      - "images_url"
      - "is_urgent"
      - "price"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      category_id:
        type: "integer"
        format: "int64"
      creation_date:
        type: "string"
        format: "yyyy-MM-dd'T'HH:mm:ssZ"
      description:
        type: "string"
      is_urgent:
        type: "boolean"
      images_url:
        $ref: "#/definitions/ImagesURL"
      price:
        type: "number"
        format: "float"
      siret:
        type: "string"
  ImagesURL:
    type: "object"
    properties:
      small:
        type: "string"
      thumb:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"